In [3]:
import pandas as pd
import numpy as np
import plotly
import plotly.express as px
from datetime import datetime
import glob

In [4]:
path = "Klines1hbtcusdtraw"
all_files = glob.glob(path + "/*.csv")
print(all_files)
df1 = pd.read_csv("Klines1hbtcusdtraw/BTCUSDT-1h-2020-01.csv")
df2 = pd.read_csv("Klines1hbtcusdtraw/BTCUSDT-1h-2020-02.csv")
df1

['Klines1hbtcusdtraw/BTCUSDT-1h-2021-05.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-02.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-12.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-08.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-10.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-01.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-06.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-09.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-05.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-07.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-03.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-08.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-02.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-07.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-10.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-04.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-03.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-01.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-04.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-09.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-06.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-11.csv']

,1577836800000,7189.43,7190.52,7170.15,7171.55,2449.049,1577840399999,17576424.43970,3688,996.198,7149370.76353,0
0,1577840400000,7171.43,7225.00,7171.10,7210.24,3865.038,1577843999999,2.783805e+07,6635,2340.878,1.686029e+07,0
1,1577844000000,7210.38,7239.30,7206.46,7237.99,3228.365,1577847599999,2.332481e+07,5120,1774.145,1.281847e+07,0
2,1577847600000,7237.41,7239.74,7215.00,7221.65,2513.307,1577851199999,1.816182e+07,4143,1245.065,8.996219e+06,0
3,1577851200000,7221.80,7225.41,7211.22,7213.86,1176.666,1577854799999,8.493631e+06,1966,586.864,4.236084e+06,0
4,1577854800000,7213.86,7224.09,7213.86,7220.31,928.221,1577858399999,6.700390e+06,1763,517.394,3.734697e+06,0
...,...,...,...,...,...,...,...,...,...,...,...,...
738,1580497200000,9330.28,9335.44,9310.42,9316.86,2689.172,1580500799999,2.506853e+07,4032,1347.985,1.256633e+07,0
739,1580500800000,9316.76,9355.33,9316.76,9338.50,4762.575,1580504399999,4.447076e+07,7662,2413.413,2.253478e+07,0
740,1580504400000,9338.28,9382.91,9331.00,9375.93,4290.714,1580507999999,4.015141e+07,7707,2351.487,2.200459e+07,0
741,1580508000000,9375.94,9438.00,9351.00,9415.24,5809.682,1580511599999,5.461509e+07,12193,3200.350,3.008727e+07,0
742,1580511600000,9415.25,9432.50,9341.00,9364.51,6078.196,1580515199999,5.705870e+07,11341,2839.071,2.665088e+07,0

In [5]:
df2

,1580515200000,9364.50,9407.14,9357.42,9394.21,4692.986,1580518799999,44028166.69423,9060,2396.962,22486856.19133,0
0,1580518800000,9394.20,9445.52,9388.39,9439.84,5907.632,1580522399999,5.561642e+07,10977,3061.587,2.882348e+07,0
1,1580522400000,9439.81,9477.76,9417.44,9452.51,7428.672,1580525999999,7.021848e+07,13973,3937.896,3.722337e+07,0
2,1580526000000,9452.51,9468.00,9412.03,9441.56,4982.520,1580529599999,4.701732e+07,8473,2328.249,2.197457e+07,0
3,1580529600000,9441.60,9460.55,9410.00,9411.63,4128.396,1580533199999,3.897168e+07,7393,2022.965,1.909996e+07,0
4,1580533200000,9412.22,9427.29,9394.98,9394.99,3575.098,1580536799999,3.364964e+07,5601,1511.943,1.423244e+07,0
...,...,...,...,...,...,...,...,...,...,...,...,...
690,1583002800000,8672.59,8683.00,8641.05,8680.00,2733.959,1583006399999,2.368511e+07,5773,1349.009,1.168643e+07,0
691,1583006400000,8679.89,8679.89,8650.00,8664.13,2054.441,1583009999999,1.779472e+07,4139,899.951,7.795200e+06,0
692,1583010000000,8664.01,8671.41,8620.00,8641.88,3305.968,1583013599999,2.855231e+07,7030,1452.493,1.254440e+07,0
693,1583013600000,8642.03,8645.93,8603.00,8643.30,2210.601,1583017199999,1.906489e+07,5593,1064.667,9.181615e+06,0
694,1583017200000,8643.30,8666.66,8530.00,8531.98,7819.600,1583020799999,6.713594e+07,16145,3082.801,2.648168e+07,0

In [7]:
df1.columns = [
    "date",
    "open",
    "high",
    "low",
    "close",
    "RL",
    "closetime",
    "ignore1",
    "ignore2",
    "ignore3",
    "ignore4",
    "ignore5",
]
df1

,date,open,high,low,close,RL,closetime,ignore1,ignore2,ignore3,ignore4,ignore5
0,1577840400000,7171.43,7225.00,7171.10,7210.24,3865.038,1577843999999,2.783805e+07,6635,2340.878,1.686029e+07,0
1,1577844000000,7210.38,7239.30,7206.46,7237.99,3228.365,1577847599999,2.332481e+07,5120,1774.145,1.281847e+07,0
2,1577847600000,7237.41,7239.74,7215.00,7221.65,2513.307,1577851199999,1.816182e+07,4143,1245.065,8.996219e+06,0
3,1577851200000,7221.80,7225.41,7211.22,7213.86,1176.666,1577854799999,8.493631e+06,1966,586.864,4.236084e+06,0
4,1577854800000,7213.86,7224.09,7213.86,7220.31,928.221,1577858399999,6.700390e+06,1763,517.394,3.734697e+06,0
...,...,...,...,...,...,...,...,...,...,...,...,...
738,1580497200000,9330.28,9335.44,9310.42,9316.86,2689.172,1580500799999,2.506853e+07,4032,1347.985,1.256633e+07,0
739,1580500800000,9316.76,9355.33,9316.76,9338.50,4762.575,1580504399999,4.447076e+07,7662,2413.413,2.253478e+07,0
740,1580504400000,9338.28,9382.91,9331.00,9375.93,4290.714,1580507999999,4.015141e+07,7707,2351.487,2.200459e+07,0
741,1580508000000,9375.94,9438.00,9351.00,9415.24,5809.682,1580511599999,5.461509e+07,12193,3200.350,3.008727e+07,0
742,1580511600000,9415.25,9432.50,9341.00,9364.51,6078.196,1580515199999,5.705870e+07,11341,2839.071,2.665088e+07,0

In [8]:
df2.columns = [
    "date",
    "open",
    "high",
    "low",
    "close",
    "RL",
    "closetime",
    "ignore1",
    "ignore2",
    "ignore3",
    "ignore4",
    "ignore5",
]
df2

,date,open,high,low,close,RL,closetime,ignore1,ignore2,ignore3,ignore4,ignore5
0,1580518800000,9394.20,9445.52,9388.39,9439.84,5907.632,1580522399999,5.561642e+07,10977,3061.587,2.882348e+07,0
1,1580522400000,9439.81,9477.76,9417.44,9452.51,7428.672,1580525999999,7.021848e+07,13973,3937.896,3.722337e+07,0
2,1580526000000,9452.51,9468.00,9412.03,9441.56,4982.520,1580529599999,4.701732e+07,8473,2328.249,2.197457e+07,0
3,1580529600000,9441.60,9460.55,9410.00,9411.63,4128.396,1580533199999,3.897168e+07,7393,2022.965,1.909996e+07,0
4,1580533200000,9412.22,9427.29,9394.98,9394.99,3575.098,1580536799999,3.364964e+07,5601,1511.943,1.423244e+07,0
...,...,...,...,...,...,...,...,...,...,...,...,...
690,1583002800000,8672.59,8683.00,8641.05,8680.00,2733.959,1583006399999,2.368511e+07,5773,1349.009,1.168643e+07,0
691,1583006400000,8679.89,8679.89,8650.00,8664.13,2054.441,1583009999999,1.779472e+07,4139,899.951,7.795200e+06,0
692,1583010000000,8664.01,8671.41,8620.00,8641.88,3305.968,1583013599999,2.855231e+07,7030,1452.493,1.254440e+07,0
693,1583013600000,8642.03,8645.93,8603.00,8643.30,2210.601,1583017199999,1.906489e+07,5593,1064.667,9.181615e+06,0
694,1583017200000,8643.30,8666.66,8530.00,8531.98,7819.600,1583020799999,6.713594e+07,16145,3082.801,2.648168e+07,0

In [12]:
df = df1
df = pd.DataFrame(df, columns=["date", "open", "high", "low", "close"])
lsnumday = []
lsweekday = []
lsvar = []
lst = []
dictdays = {
    0: "Monday",
    1: "Tuesday",
    2: "Wednesday",
    3: "Thursday",
    4: "Friday",
    5: "Saturday",
    6: "Sunday",
}
for n in range(len(df)):
    ts = df.iloc[n, 0] / 1000
    dt = datetime.fromtimestamp(ts)
    df.iloc[n, 0] = dt
    weekd = datetime.weekday(df.iloc[n, 0])
    lsnumday.append(weekd)
    var = df.iloc[n, 4] / df.iloc[n, 1] * 100 - 100
    lsvar.append(var)
for item in lsnumday:
    lsweekday.append(dictdays[item])
df["weekday"] = lsweekday
df["variation"] = lsvar
for n in range(len(df)):
    dtm = df.iloc[n, 0]
    tm = dtm.time()
    lst.append(tm)
df["opentime"] = lst
df

,date,open,high,low,close,weekday,variation,opentime
0,2020-01-01 02:00:00,7171.43,7225.00,7171.10,7210.24,Wednesday,0.541175,02:00:00
1,2020-01-01 03:00:00,7210.38,7239.30,7206.46,7237.99,Wednesday,0.382920,03:00:00
2,2020-01-01 04:00:00,7237.41,7239.74,7215.00,7221.65,Wednesday,-0.217757,04:00:00
3,2020-01-01 05:00:00,7221.80,7225.41,7211.22,7213.86,Wednesday,-0.109945,05:00:00
4,2020-01-01 06:00:00,7213.86,7224.09,7213.86,7220.31,Wednesday,0.089411,06:00:00
...,...,...,...,...,...,...,...,...
738,2020-01-31 20:00:00,9330.28,9335.44,9310.42,9316.86,Friday,-0.143833,20:00:00
739,2020-01-31 21:00:00,9316.76,9355.33,9316.76,9338.50,Friday,0.233343,21:00:00
740,2020-01-31 22:00:00,9338.28,9382.91,9331.00,9375.93,Friday,0.403179,22:00:00
741,2020-01-31 23:00:00,9375.94,9438.00,9351.00,9415.24,Friday,0.419158,23:00:00
742,2020-02-01 00:00:00,9415.25,9432.50,9341.00,9364.51,Saturday,-0.538913,00:00:00