In [102]:
import pandas as pd
import numpy as np
import plotly
import plotly.express as px
from datetime import datetime
import datetime
import glob

In [103]:
def get_df (csvfile):
    df = pd.read_csv(csvfile)
    df.columns = [
    "date",
    "open",
    "high",
    "low",
    "close",
    "RL",
    "closetime",
    "ignore1",
    "ignore2",
    "ignore3",
    "ignore4",
    "ignore5",
    ]
    df = pd.DataFrame(df, columns=["date", "open", "high", "low", "close"])
    lsnumday = []
    lsweekday = []
    lsvar = []
    lst = []
    dictdays = {
        0: "Monday",
        1: "Tuesday",
        2: "Wednesday",
        3: "Thursday",
        4: "Friday",
        5: "Saturday",
        6: "Sunday",
    }
    for n in range(len(df)):
        ts = df.iloc[n, 0] / 1000
        dt = datetime.fromtimestamp(ts)
        df.iloc[n, 0] = dt
        weekd = datetime.weekday(df.iloc[n, 0])
        lsnumday.append(weekd)
        var = df.iloc[n, 4] / df.iloc[n, 1] * 100 - 100
        lsvar.append(var)
    for item in lsnumday:
        lsweekday.append(dictdays[item])
    df["weekday"] = lsweekday
    df["variation"] = lsvar
    for n in range(len(df)):
        dtm = df.iloc[n, 0]
        tm = dtm.time()
        lst.append(tm)
        print(lst)
    df["opentime"] = lst
    return df

In [104]:

df1 = get_df("Klines1hbtcusdtraw/BTCUSDT-1h-2020-01.csv")
df2 = get_df("Klines1hbtcusdtraw/BTCUSDT-1h-2020-02.csv")
df1
df1 = df1.append(df2, ignore_index = True)
df1

AttributeError: module 'datetime' has no attribute 'fromtimestamp'

Fonction pour regrouper tout en 1 DF

In [ ]:
def group_df(folder):
    path = folder
    all_files = glob.glob(path + "/*.csv")
    print(all_files)
    n=0
    df = pd.DataFrame()
    for file in all_files:
        if n == 0:
            df = get_df(file)
            df
            n+=1
        else:
            df2 = get_df(file)
            df = df.append(df2, ignore_index=True)
            
    return df

df = group_df("Klines1hbtcusdtraw")

['Klines1hbtcusdtraw/BTCUSDT-1h-2020-09.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-12.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-10.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-05.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-07.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-08.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-04.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-08.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-05.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-02.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-01.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-03.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-06.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-10.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-09.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-02.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2021-03.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-07.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-04.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-01.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-06.csv', 'Klines1hbtcusdtraw/BTCUSDT-1h-2020-11.csv']

In [ ]:
df

,date,open,high,low,close,weekday,variation,opentime
0,2020-09-01 03:00:00,11618.27,11643.75,11593.00,11634.31,Tuesday,0.138058,03:00:00
1,2020-09-01 04:00:00,11634.32,11649.56,11615.00,11635.90,Tuesday,0.013581,04:00:00
2,2020-09-01 05:00:00,11635.90,11710.00,11623.02,11698.75,Tuesday,0.540139,05:00:00
3,2020-09-01 06:00:00,11698.75,11728.98,11686.00,11702.26,Tuesday,0.030003,06:00:00
4,2020-09-01 07:00:00,11702.26,11810.93,11693.44,11805.78,Tuesday,0.884615,07:00:00
...,...,...,...,...,...,...,...,...
16053,2020-11-30 20:00:00,19201.40,19337.39,19108.89,19275.44,Monday,0.385597,20:00:00
16054,2020-11-30 21:00:00,19273.92,19506.50,19185.00,19446.45,Monday,0.895147,21:00:00
16055,2020-11-30 22:00:00,19446.45,19550.00,19334.01,19390.00,Monday,-0.290284,22:00:00
16056,2020-11-30 23:00:00,19390.00,19519.57,19258.30,19519.56,Monday,0.668179,23:00:00
16057,2020-12-01 00:00:00,19519.57,19775.34,19461.31,19720.00,Tuesday,1.026816,00:00:00

In [ ]:
def gather_info(df):

    df2 = pd.DataFrame(columns= ["weekday", "opentime", "mean", "med", "ratio"])
    lsweekday = df.weekday.unique().tolist()
    lshours = df.opentime.unique().tolist()
    dicta = {}
    l = 0
    for day in lsweekday:
        for hour in lshours:
            x=0
            ls = []
            pos = 0
            neg = 0
            for n in range(len(df)):
                if df.iloc[n, 5] == day and df.iloc[n, 7] == hour :
                    var = df.iloc[n, 6]
                    print(var)
                    ls.append(var)
                    if var >= 0:
                        pos += 1
                    else:
                        neg +=1
            mean = np.mean(ls)
            med = np.median(ls)
            ratio = ((pos/(pos+neg)*100))
            print("{} {} {}".format(mean, med, ratio))
            ls = [day, hour, mean, med, ratio]
            df2.loc[x] = ls
            #print(df2)
            x+=1
    return df2
#df = gather_info(df)

In [ ]:
df
df.index = df.weekday
df = df.filter(like="Monday", axis  = 0)
df

,date,open,high,low,close,weekday,variation,opentime
weekday,,,,,,,,
Monday,2020-09-07 00:00:00,10322.41,10348.97,10186.00,10212.73,Monday,-1.062543,00:00:00
Monday,2020-09-07 01:00:00,10212.20,10312.00,10191.78,10258.13,Monday,0.449756,01:00:00
Monday,2020-09-07 02:00:00,10258.13,10315.13,10243.00,10282.80,Monday,0.240492,02:00:00
Monday,2020-09-07 03:00:00,10282.81,10290.00,10233.52,10286.06,Monday,0.031606,03:00:00
Monday,2020-09-07 04:00:00,10286.05,10286.06,10196.00,10211.70,Monday,-0.722824,04:00:00
...,...,...,...,...,...,...,...,...
Monday,2020-11-30 19:00:00,19415.88,19494.79,19163.96,19201.40,Monday,-1.104663,19:00:00
Monday,2020-11-30 20:00:00,19201.40,19337.39,19108.89,19275.44,Monday,0.385597,20:00:00
Monday,2020-11-30 21:00:00,19273.92,19506.50,19185.00,19446.45,Monday,0.895147,21:00:00
Monday,2020-11-30 22:00:00,19446.45,19550.00,19334.01,19390.00,Monday,-0.290284,22:00:00
Monday,2020-11-30 23:00:00,19390.00,19519.57,19258.30,19519.56,Monday,0.668179,23:00:00

In [ ]:
df.index = df.opentime
df

,date,open,high,low,close,weekday,variation,opentime
opentime,,,,,,,,
00:00:00,2020-09-07 00:00:00,10322.41,10348.97,10186.00,10212.73,Monday,-1.062543,00:00:00
01:00:00,2020-09-07 01:00:00,10212.20,10312.00,10191.78,10258.13,Monday,0.449756,01:00:00
02:00:00,2020-09-07 02:00:00,10258.13,10315.13,10243.00,10282.80,Monday,0.240492,02:00:00
03:00:00,2020-09-07 03:00:00,10282.81,10290.00,10233.52,10286.06,Monday,0.031606,03:00:00
04:00:00,2020-09-07 04:00:00,10286.05,10286.06,10196.00,10211.70,Monday,-0.722824,04:00:00
...,...,...,...,...,...,...,...,...
19:00:00,2020-11-30 19:00:00,19415.88,19494.79,19163.96,19201.40,Monday,-1.104663,19:00:00
20:00:00,2020-11-30 20:00:00,19201.40,19337.39,19108.89,19275.44,Monday,0.385597,20:00:00
21:00:00,2020-11-30 21:00:00,19273.92,19506.50,19185.00,19446.45,Monday,0.895147,21:00:00
22:00:00,2020-11-30 22:00:00,19446.45,19550.00,19334.01,19390.00,Monday,-0.290284,22:00:00
23:00:00,2020-11-30 23:00:00,19390.00,19519.57,19258.30,19519.56,Monday,0.668179,23:00:00

In [ ]:
df.iloc[4, 7]

datetime.time(4, 0)

In [ ]:
df.filter(like = datetime.datetime.time(4, 0), axis = 0)

TypeError: descriptor 'time' for 'datetime.datetime' objects doesn't apply to a 'int' object